/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gpays;

import static Gpays.CESC.showallnumbers2;
import static Gpays.MobileRecharge.showallnumbers;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class Paybills extends javax.swing.JFrame {

    /**
     * Creates new form Paybills
     */
    public Paybills() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        acctrans = new javax.swing.JLabel();
        cesc = new javax.swing.JLabel();
        recharge = new javax.swing.JLabel();
        others = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        avatar2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(169, 222, 134));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/FzxBBPrs-removebg-preview.png"))); // NOI18N
        jLabel2.setText("Google Pay");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 80));

        acctrans.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        acctrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/surr-575.png"))); // NOI18N
        acctrans.setText("Account Transfer");
        acctrans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acctrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acctransMouseClicked(evt);
            }
        });
        jPanel1.add(acctrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 230, -1));

        cesc.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/flame-1259.png"))); // NOI18N
        cesc.setText("CESE");
        cesc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cescMouseClicked(evt);
            }
        });
        jPanel1.add(cesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 180, -1));

        recharge.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        recharge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/f2.png"))); // NOI18N
        recharge.setText("Mobile Recharge");
        recharge.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recharge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rechargeMouseClicked(evt);
            }
        });
        jPanel1.add(recharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        others.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        others.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/spot-127.png"))); // NOI18N
        others.setText("Others");
        others.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        others.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                othersMouseClicked(evt);
            }
        });
        jPanel1.add(others, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 200, -1));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("X");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 20, -1));

        avatar2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        avatar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/1.png"))); // NOI18N
        jPanel1.add(avatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 70));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        jLabel10.setText("PAY YOUR BILLS WITH SECURE & TRUST.");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","");
            String query1=" select * from account where Name='"+avatar2.getText()+"' ";
            Statement stt=con.createStatement();                
                ResultSet rss=stt.executeQuery(query1); 
                if(rss.next()){
                   String Na=rss.getString("Name");                   
                   dispose();
                    Main m=new Main();
                    m.setVisible(true);
                    m.avatar.setText(Na);                   
                    
                }else{
                JOptionPane.showMessageDialog(null,"Error");                
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void acctransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acctransMouseClicked
        // TODO add your handling code here:
        
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","");
            String query1=" select * from account where Name='"+avatar2.getText()+"' ";
            
            Statement stt=con.createStatement();                
                ResultSet rss=stt.executeQuery(query1);  
                
                 if(rss.next()){
                   String Na=rss.getString("Name");
                   String accn=rss.getString("AccountNo");
                   AccountTransfer at=new AccountTransfer();
                    at.setVisible(true);                
                    dispose();
                    at.avatar3.setText(Na);
                    at.acc.setText(accn);
                    
                }else{
                JOptionPane.showMessageDialog(null,"Error");
                
                }
        }catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
            System.out.println(e);
        }
        
       
        
    }//GEN-LAST:event_acctransMouseClicked

    private void othersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_othersMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"ON Maintaince...!");
    }//GEN-LAST:event_othersMouseClicked

    private void rechargeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechargeMouseClicked
        // TODO add your handling code here:
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","");
            String query1=" select * from account where Name='"+avatar2.getText()+"' ";
            
            Statement stt=con.createStatement();                
                ResultSet rss=stt.executeQuery(query1);  
                
                 if(rss.next()){
                   String Na=rss.getString("Name");
                   String accn=rss.getString("AccountNo");
                   MobileRecharge m=new MobileRecharge();
                    m.setVisible(true);
                    dispose();              
                    
                    m.na.setText(Na);
                    m.accno.setText(accn);
                    showallnumbers();
                    
                }else{
                JOptionPane.showMessageDialog(null,"Error");
                
                }
        }catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
            System.out.println(e);
        }
        
    }//GEN-LAST:event_rechargeMouseClicked

    private void cescMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cescMouseClicked
        // TODO add your handling code here:
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","");
            String query1=" select * from account where Name='"+avatar2.getText()+"' ";
            
            Statement stt=con.createStatement();                
                ResultSet rss=stt.executeQuery(query1);  
                
                 if(rss.next()){
                   String Na=rss.getString("Name");
                   String accn=rss.getString("AccountNo");
                   CESC m=new CESC();
                    m.setVisible(true);
                    dispose();              
                    
                    m.av.setText(Na);
                    m.acc.setText(accn);
                    showallnumbers2();
                }else{
                JOptionPane.showMessageDialog(null,"Error");
                
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            System.out.println(e);
        }
    }//GEN-LAST:event_cescMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paybills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paybills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paybills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paybills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paybills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acctrans;
    public static javax.swing.JLabel avatar2;
    private javax.swing.JLabel cesc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel others;
    private javax.swing.JLabel recharge;
    // End of variables declaration//GEN-END:variables
}
