/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pins;

import Gpays.AccountTransfer;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author ADMIN
 */
public class accpin extends javax.swing.JFrame {
 PreparedStatement pa=null; 
PreparedStatement pa2=null;
    /**
     * Creates new form accpin
     */
    public accpin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        na22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        upi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        na22.setText("xx");
        jPanel1.add(na22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton1.setText("Send");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));
        jPanel1.add(upi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 150, 30));

        jLabel1.setText("Enter Pin");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 220));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        AccountTransfer t=new AccountTransfer();        
        String amat=AccountTransfer.amt.getText();
        String accno1=AccountTransfer.accno.getText();
        String cif1=AccountTransfer.cif.getText();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
          
        try
        {
          
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","");
            Statement st1=con.createStatement();
            ResultSet rs1 = st1.executeQuery("select Pin from account where Name='"+na22.getText()+"' ");
            if(rs1.next())
            {
                String ch=rs1.getString("Pin");
                String ch4= upi.getText();
            
            if( ch.equals(ch4))
            {
                
                try{
                    
                    try (Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","")) {
                        Statement st=con1.createStatement();
                        con1.setAutoCommit(false);
                        String query="UPDATE `account` SET `Deposit`=Deposit-"+amat+" WHERE Pin='"+upi.getText()+"'";
                        String query2="UPDATE `account` SET `Deposit`=Deposit+"+amat+" WHERE AccountNo='"+accno1+"'and CIF='"+cif1+"'";
                        pa=con1.prepareStatement(query);
                        pa2=con1.prepareStatement(query2);
                        
                        pa.executeUpdate(); 
                        pa2.executeUpdate();
                        JOptionPane.showMessageDialog(null,"Sucessfully Transfered...!");
                    }
            }
                catch(Exception e){
                JOptionPane.showMessageDialog(null,"Server Down");
                System.out.println(e);
            }
                
            }
            
            else{
                JOptionPane.showMessageDialog(null,"Invalid Pin");
            }
            }
            else{
              JOptionPane.showMessageDialog(null,"Result Set Problem");  
            }
            
            
        }
        catch(Exception ee){
            System.out.println(ee);
            JOptionPane.showMessageDialog(null,"Pin Error");
        }       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accpin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accpin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accpin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accpin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accpin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel na22;
    private javax.swing.JTextField upi;
    // End of variables declaration//GEN-END:variables
}
